---
gps_info:
  analyzed_variables: "null"
  fallback_protocol: land
  importance: executive
fcu_health:
  analyzed_variables: "null"
  fallback_protocol: land
  importance: executive
battery_info:
  analyzed_variables: "null"
  fallback_protocol: rtl
  importance: executive